// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtFg4GY2H331XN9E7UORv7gIj6qROTG9Y',
    appId: '1:1021496073675:web:a543a4b4fec56ac11cea4e',
    messagingSenderId: '1021496073675',
    projectId: 'restaurant-package-booki-182ab',
    authDomain: 'restaurant-package-booki-182ab.firebaseapp.com',
    databaseURL: 'https://restaurant-package-booki-182ab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'restaurant-package-booki-182ab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKwrIUpNe_imQVK3O946HxwPZ1ktoexoA',
    appId: '1:1021496073675:android:9af727d3a486394b1cea4e',
    messagingSenderId: '1021496073675',
    projectId: 'restaurant-package-booki-182ab',
    databaseURL: 'https://restaurant-package-booki-182ab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'restaurant-package-booki-182ab.firebasestorage.app',
  );
}
